name: Build and Deploy FrontEnd app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Login into docker
      uses: docker/login-action@v3.2.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}

    - name: Set up Docker Build and Push
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags:
          copapel/lar_renascer:latest