FROM node:21 as build

RUN mkdir /lar_renascer

WORKDIR /lar_renascer

COPY package.json package-lock.json /lar_renascer/

RUN npm install

COPY . /lar_renascer

RUN npm run build

FROM nginx:latest

COPY --from=build /lar_renascer/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8004
